version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: weatherapi
    container_name: weatherapi
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
